name: build curl

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [armv7, arm64, x86, x86_64]
    name: Build curl for ${{ matrix.arch }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c

      - name: Set ANDROID_NDK_ROOT Env
        run: |
          echo "ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}"

      - name: Build curl
        run: |
          sh build_android.sh --arch ${{ matrix.arch }}

      - name: Upload .h and .a files
        uses: actions/upload-artifact@v4
        with:
          name: curl-android-${{ matrix.arch }}
          path: |
            out/**/include/**/*.h
            out/**/lib/*.a
            out/**/lib/*.so
